---
repository:
  name: .github
  description: Shared Github settings for GRS Service GmbH
  homepage: https://www.grs-batterien.de/
  topics:
  - configuration
  private: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
...
